# Generated by Django 4.0.6 on 2022-07-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_email'),
        ('classes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='students',
        ),
        migrations.AddField(
            model_name='classes',
            name='students',
            field=models.ManyToManyField(related_name='classes', to='student.student'),
        ),
    ]
