# Generated by Django 4.0.6 on 2022-07-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='first_name')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='full_name')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date_of_birth')),
                ('address', models.TextField(blank=True, null=True, verbose_name='address')),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=6, null=True, verbose_name='gender')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='students/')),
            ],
        ),
    ]
